### ISSUE TITLE
showing error "Manifest file is missing or unreadable."

### ISSUE THREAD

**Issue by tiddu** [jwillmer/web-scraper-chrome-extension#11]

**Comment by kznmft** [comment]
Hello,

Did you load the extension folder?

**Comment by tiddu** [comment]
yes , i tried to add the folder via the "load unpacked extension" , and also by dragging. i tried my default chrome and a portable chrome , i also checked the json extension , also the file is in utf format rather than ansi.

**Comment by kznmft** [comment]
1. how did you download the code? downloaded as a zip?
2. when you go into the extension folder does the manifest.json file is present?
3. Permission issues? does the user you have launched Chrome with has access to the folder?

**Comment by tiddu** [comment]
i checked all , i downloaded it as zip , and manifest file is present , and no permission problem. i am actually scraping through downloaded pages, i downloaded 9k pages via idm , and use webserver app to set localhost and i want to scrape through those 9k files , there should be no delay settings in this extension too , but first i coudlnt even load this extension.

**Comment by tiddu** [comment]
ok , issue is solved now , i was dragging the full folder rather than the extension folder , also the zip file downloaded doesnt have the css selector folder contents . so , i downloaded them separately and merge , and than i can load the extension easily.

**Comment by kznmft** [comment]
great. glad you solved it. 
Indeed adding css selector folder was the next step.
I was just preparing to send you a folder with only the extension + css selector dependency.

can you please close the issue?

thanks!
