### ISSUE TITLE
option of zero delays etc in case of scraping from local files

### ISSUE THREAD

**Issue by tiddu** [jwillmer/web-scraper-chrome-extension#12]
i am scraping through downloaded pages, i downloaded 9k pages via idm , and i want to scrape through those 9k files , there should be no delay settings in this extension too ,

**Comment by kznmft** [comment]
hello,

you can modify the timeouts:

1. https://github.com/jwillmer/web-scraper-chrome-extension/blob/master/extension/scripts/Controller.js#L1024
2. https://github.com/jwillmer/web-scraper-chrome-extension/blob/master/extension/scripts/Scraper.js#L17

after you modify go to extensions page and reload your extension.

**Comment by tiddu** [comment]
thanks bud
