### ISSUE TITLE
URL not valid when creating sitemap

### ISSUE THREAD

**Issue by efritz89** [jwillmer/web-scraper-chrome-extension#13]
URLs are not appearing valid when creating a new sitemap. 

New install, downloaded files, extracted files and uploaded Extension folder into Chrome extensions. I had to directly download Extension>Assets>CSS Selector from github and drop files into CSS Selector folder as it was empty and extension would not install.
![url error](https://user-images.githubusercontent.com/30202870/28242705-cb7b7f98-6980-11e7-81f7-fadd4e9e0cae.PNG)

**Comment by jwillmer** [comment]
I can reproduce both bugs. Will take a look.

**Comment by jwillmer** [comment]
Please check and close the issue if it is solved.

**Comment by efritz89** [comment]
Version 0.3.1 allowed me to add a new URL. I will close the issue. Thank you.
