### ISSUE TITLE
Extension folder missing CSS Selector data when downloaded from GitHub

### ISSUE THREAD

**Issue by efritz89** [jwillmer/web-scraper-chrome-extension#14]
Install failed initially due to CSS Selector folder being empty. 

I downloaded the project, extracted and attempted to install the extensions folder. I received an error that I was missing contents from the Extension>Assets>CSS Selector folder. Upon further inspection the folder was empty. I opened the project and manually downloaded the CSS Selector folder, extracted and pasted contents into the local folder. Install then completed successfully.

**Comment by jwillmer** [comment]
This is because another repository is referenced (linked). I will manually create a ZIP for a better installation experience.

**Comment by jwillmer** [comment]
I added a [release](https://github.com/jwillmer/web-scraper-chrome-extension/releases) with a ZIP that contains the extension and updated the README.
