### ISSUE TITLE
How to implement random delay?

### ISSUE THREAD

**Issue by djm96** [jwillmer/web-scraper-chrome-extension#15]
"Added random delay function between requests" is in the change long for v0.3 but I can't seem to find how to implement the random delays. It's not mentioned in the documentation and I don't see any clear way to use the feature in the web scraper. I only see an input for a single, consistent, delay.

Any guidance on how to use this feature would be appreciated!

**Comment by jwillmer** [comment]
In the source code: 
```
this._timeNextScrapeAvailable = now + this.requestInterval + Math.random()*this.requestIntervalRandomness
```

This is the commit: https://github.com/jwillmer/web-scraper-chrome-extension/commit/9b433385bc54fd3ab4deba45cad367b90e9117bf

**Comment by jwillmer** [comment]
Closing this since lack of activity.
